# Generated by Django 5.0.6 on 2026-05-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, help_text='Height in centimetres (50–300).', max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms (1–500).', max_digits=5)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Waist circumference in centimetres (30–300). Optional — required for WtHR.', max_digits=5, null=True)),
                ('age', models.PositiveSmallIntegerField(help_text='Age in years (1–120).')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'body measurement',
            },
        ),
        migrations.CreateModel(
            name='HealthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ibw_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wthr', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('lbm_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bfp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='health.bodymeasurement')),
            ],
            options={
                'verbose_name': 'health result',
            },
        ),
    ]
